'use client';

import Image from 'next/image';
import Link from 'next/link';
import { getPlaceholderImage } from '@/lib/placeholder-images';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowRight, Footprints, Info } from 'lucide-react';

export default function HomePage() {
    const heroImage = getPlaceholderImage('hero-nature');

    return (
        <div className="space-y-12">
            <Card className="overflow-hidden shadow-lg">
                <div className="relative h-80 w-full">
                    {heroImage && (
                        <Image
                            src={heroImage.imageUrl}
                            alt={heroImage.description}
                            data-ai-hint={heroImage.imageHint}
                            fill
                            className="object-cover"
                            priority
                        />
                    )}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" />
                    <div className="absolute bottom-0 left-0 p-8">
                        <h1 className="text-5xl font-bold font-headline text-white drop-shadow-md">Welcome to EcoTrack</h1>
                        <p className="text-xl text-white/90 mt-2 max-w-2xl">Your journey to a smaller carbon footprint starts now. Let's make a difference, one week at a time.</p>
                    </div>
                </div>
                 <CardContent className="p-8 bg-gray-50 dark:bg-card">
                    <p className="text-lg mb-6 text-gray-700 dark:text-gray-300">
                        Take control of your environmental impact. Log your weekly activities to understand and reduce your carbon footprint with personalized, AI-driven advice.
                    </p>
                    <div className="flex gap-4">
                        <Button asChild size="lg">
                            <Link href="/dashboard">
                                View Your Dashboard
                                <ArrowRight className="ml-2" />
                            </Link>
                        </Button>
                        <Button asChild size="lg" variant="secondary">
                            <Link href="/log">
                                Log Your First Week
                            </Link>
                        </Button>
                    </div>
                </CardContent>
            </Card>

            <div className="grid md:grid-cols-3 gap-8">
                <div className="md:col-span-2">
                    <h2 className="text-3xl font-bold font-headline mb-4">What is a Carbon Footprint?</h2>
                    <div className="space-y-4 text-muted-foreground">
                        <p>
                            A carbon footprint is the total amount of greenhouse gases—primarily carbon dioxide (CO₂)—that are generated by our actions. It's a way to measure our individual and collective impact on the environment.
                        </p>
                        <p>
                            Everyday activities, from the food we eat to the way we travel, contribute to our footprint. The main sources typically include:
                        </p>
                         <ul className="list-disc list-inside space-y-2 pl-2">
                            <li><strong>Transportation:</strong> Driving cars, flying, and using public transport.</li>
                            <li><strong>Home Energy:</strong> Electricity for lighting and appliances, and gas for heating and cooking.</li>
                            <li><strong>Food:</strong> The production, processing, and transportation of food, especially meat and dairy products.</li>
                            <li><strong>Consumption:</strong> The manufacturing and disposal of products we buy.</li>
                        </ul>
                    </div>
                </div>
                <Card className="bg-secondary/50">
                    <CardHeader>
                        <div className="flex items-start gap-4">
                            <div className="bg-primary/10 text-primary p-3 rounded-full">
                                <Footprints className="h-6 w-6" />
                            </div>
                            <div>
                                <CardTitle className="text-xl">Why Track It?</CardTitle>
                            </div>
                        </div>
                    </CardHeader>
                    <CardContent>
                        <p className="text-muted-foreground">
                            By understanding your carbon footprint, you can identify the biggest areas of impact and make informed choices to reduce it. Small changes in our daily habits can collectively lead to a significant positive effect on the planet. EcoTrack helps you see where you stand and guides you toward a more sustainable lifestyle.
                        </p>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
